logging:
  level:
    root: info

mysql:
  username: root
  password: 123456
  schema: adm_videos
  url: localhost:${mysql.port}

amqp:
  host: localhost
  port: 5672
  username: adm_videos
  password: 123456

spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.amqp.RabbitAutoConfiguration

keycloak:
  realm: test
  host: http://test:8443