amqp:
  host: ${AMQP_RABBIT_HOST}
  port: ${AMQP_RABBIT_PORT}
  username: ${AMQP_RABBIT_USERNAME}
  password: ${AMQP_RABBIT_PASSWORD}

mysql:
  username: ${DATABASE_MYSQL_USERNAME:root}
  password: ${DATABASE_MYSQL_PASSWORD:123456}
  schema: adm_videos
  url: ${DATABASE_MYSQL_URL:localhost:3306}

spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none

keycloak:
  realm: ${KEYCLOAK_REALM:admin-catalogo-de-videos}
  host: ${KEYCLOAK_HOST:http://localhost:8443}