name: CI Pipeline

on:
  push:
  workflow_dispatch:

jobs:
  # Job para a execução dos testes
  tests:
    name: Test runner
    runs-on: ubuntu-latest
    steps:
      # Checkout do código fonte
      - uses: actions/checkout@v3
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Run application tests
        run: ./gradlew test